programs:
    script:
        command: '/home/srouhe/hive-projects/taskmaster/test/script.sh'
        autostart: true
        autorestart: true
        stderr_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scripterr.log'
        stdout_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scriptout.log'
        stop_signal: 'SIGTERM'
        timeout: 5
        restarts: 3
        expected_exit: [1, 3]
        startuptime: 5
        env_vars: 'pillu'
        working_dir: '/'
        umask: 022
    scriptshort:
        command: '/home/srouhe/hive-projects/taskmaster/test/scriptshort.sh'
        autostart: true
        autorestart: true
        stderr_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scriptshorterr.log'
        stdout_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scriptshortout.log'
