programs:
    script:
        command: ['/home/srouhe/hive-projects/taskmaster/test/script.sh']
        autostart: true
        autorestart: true
        stderr_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scripterr.log'
        stdout_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scriptout.log'
        stop_signal: 15
        kill_timeout: 5
        restarts: 9
        expected_exit: [1, 3]
        startup_wait: 0
        environment: 'pillu'
        dir: '/'
        umask: 022
    scriptshort:
        command: ['/home/srouhe/hive-projects/taskmaster/test/scriptshort.sh']
        autostart: false
        autorestart: false
        stderr_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scriptshorterr.log'
        stdout_logfile: '/home/srouhe/hive-projects/taskmaster/logs/scriptshortout.log'
