programs:
    script:
        command: ['./script.sh']
        autostart: true
        autorestart: 'unexpected'
        stdout_logfile: '/home/snake/Taskmaster/taskmaster/resources/logs/scriptout.log'
        instances: 3
        stop_signal: 15
        kill_timeout: 5
        restarts: 3
        expected_exit: [0, -15]
        startup_wait: 1
        environment: ['var:value', 'var2:val']
        dir: '/home/snake/Taskmaster/taskmaster/resources'
        umask: 0o22
    scriptshort:
        command: ['./scriptshort.sh']
        autostart: true
        autorestart: 'never'
        stderr_logfile: '/dev/null'
        stdout_logfile: '/dev/null'
        dir: '/home/snake/Taskmaster/taskmaster/resources'
    short_echo:
        command: ['./echo.sh']
        autostart: true
        autorestart: 'unexpected'
        expected_exit: [0]
        stderr_logfile: '/home/snake/Taskmaster/taskmaster/resources/logs/echo_out.log'
        stdout_logfile: '/home/snake/Taskmaster/taskmaster/resources/logs/echo_err.log'
        dir: '/home/snake/Taskmaster/taskmaster/resources'
    script_error:
        command: ['./script_error.sh']
        autostart: true
        autorestart: 'unexpected'
        expected_exit: [0, 1]
        stderr_logfile: '/dev/null'
        stdout_logfile: '/dev/null'
        dir: '/home/snake/Taskmaster/taskmaster/resources'
    script_umask:
        command: ['./script_umask.sh']
        autostart: true
        autorestart: 'never'
        expected_exit: [0, 1]
        stderr_logfile: '/dev/null'
        stdout_logfile: '/dev/null'
        dir: '/home/snake/Taskmaster/taskmaster/resources'
        umask: 777
server:
    port: 9999
