programs:
    script:
        command: ['./script.sh']
        autostart: true
        autorestart: 'unexpected'
        stdout_logfile: '/home/srouhe/hive-projects/taskmaster/taskmaster/resources/logs/scriptout.log'
        instances: 2
        stop_signal: 15
        kill_timeout: 5
        restarts: 9
        expected_exit: [0, -15]
        startup_wait: 0
        environment: ['var:value', 'var2:val']
        dir: '/home/srouhe/hive-projects/taskmaster/taskmaster/resources'
        umask: 0o22
    scriptshort:
        command: ['./scriptshort.sh']
        autostart: true
        autorestart: 'never'
        stderr_logfile: '/dev/null'
        stdout_logfile: '/dev/null'
        dir: '/home/srouhe/hive-projects/taskmaster/taskmaster/resources'
    short_echo:
        command: ['./echo.sh']
        autostart: true
        autorestart: 'unexpected'
        expected_exit: [0]
        stderr_logfile: '/home/srouhe/hive-projects/taskmaster/taskmaster/resources/logs/echo_out.log'
        stdout_logfile: '/home/srouhe/hive-projects/taskmaster/taskmaster/resources/logs/echo_err.log'
        dir: '/home/srouhe/hive-projects/taskmaster/taskmaster/resources'
server:
    port: 9999
